<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 EntityAudit '); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
        ?>
    </head>
    <body>
 
       <nav class="navbar navbar-default" role="navigation">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="<?php echo $this->url('application') ?>">ZF2EntityAudit</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url('application') ?>"><i class="icon-home"></i> Home</a></li>
                    <li><a href="<?php echo $this->url('audit_index') ?>"><i class="icon-edit"></i> Audit Revisions</a></li>
                    <li><a href="https://github.com/tawfekov/ZF2EntityAudit"><i class="icon-book"></i> Source Code</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                   <?php if (!$this->zfcUserIdentity()) :?>
                      <li><a href="/user/login">Sign In</a></li>
                      <li><a href="/user/register">Register</a></li>
                    <?php else:?>
                      <li><div style="padding-top: 15px"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 24)); ?></div></li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              <?php echo $this->zfcUserDisplayName() ?>
                          </a>
                      </li>
                      <li><a href="/user/logout">Logout</a></li>
                    <?php endif;?>
                  </ul>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
        </nav>

        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div class="container">
            <div>
                <hr/>
                <footer>
                    <p>&copy; 2013 <a href="https://github.com/tawfekov/ZF2EntityAudit">ZF2EntityAudit</a></p>
                </footer>
            </div>

        </div>

    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
</body>
</html>
