<h1>Edit Sample Data</h1>

<div class="row">
    <div class="span12">
        <?= $this->form()->openTag($form); ?>

        <?= $this->formRow($form->get('name')); ?>

        <?= $this->formRow($form->get('tag')); ?>

        <br>

        <?php echo $this->formInput($form->get('save')); ?>

        <a class="btn btn-danger confirm" href="/delete/<?= $type->getId(); ?>">
            Delete
        </a>

        <?= $this->form()->closeTag($form); ?>
    </div>
</div>

<script>

$(function() {
    $('.confirm').on('click', function(event) {
        return confirm('Are you sure?');
    });
});

</script>

