<h1>Edit Sample Data</h1>

<div class="row">
    <div class="span12">
        <?= $this->form()->openTag($form); ?>

        <?= $this->formRow($form->get('name')); ?>

        <?= $this->formRow($form->get('tag')); ?>

        <br>

        <?= $this->formInput(
                $form->get('save')->setAttributes(
                    array(
                        'value' => 'Update' ,
                        'class' => 'btn btn-warning'
                    )
                )
            ); ?>

        <a class="btn btn-danger confirm"
            href="<?=
            $this->url('edit' ,
                array(
                    'controller' => 'index' ,
                    'action' => 'delete' ,
                    'id' => $type->getId()
                )
            ); ?>">Delete</a>

        <?= $this->form()->closeTag($form); ?>
    </div>
</div>

<script>

$(function() {
    $('.confirm').on('click', function(event) {
        return confirm('Are you sure?');
    });
});

</script>

